print("Wow")
print("Wow")
print("Wow")
print("Wow")
print("Wow")
print("Wow")
print("Wow")
print("Wow")
print("Wow")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")
print("no way")